spring:
  cloud:
    config:
      uri: http://localhost:8888/
      label: master
      profile: dev
  application:
    name: chen-hello

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 8000
